name: Resources
on: workflow_dispatch
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: change version
              run: |
                sed -e "s/image/effi24\/myip:myipp/g"
              
            - uses: actions/setup-node@v1

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: ./values.yml
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
