name: Resources
on: workflow_dispatch
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: change version
              run: |
                sed  -i -e 's/\(^image=\).*/\1effi24/myipp/' values.yaml
              
            - uses: actions/setup-node@v1

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: path/to/file
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
